export { broadcastService } from './broadcast.js';
export { downloaderService } from './downloader.js';
export { battleService } from './combat/battle.js';
export { robService } from './combat/rob.js';
export { shopService } from './economy/shop.js';
export { divergentUniverseService } from './rpg/divergent-universe.js';
export { relicService } from './rpg/relic.js';
export { instagramService } from './platforms/instagram.js';
export { facebookService } from './platforms/facebook.js';
